ALTER TABLE "audit_log" ADD COLUMN "seq" bigserial NOT NULL;--> statement-breakpoint
ALTER TABLE "audit_log" ADD COLUMN "hash_version" integer DEFAULT 2 NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_tenant_seq_idx" ON "audit_log" USING btree ("tenant_id","seq");--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_seq_unique" UNIQUE("seq");--> statement-breakpoint

-- ─────────────────────────────────────────────────────────────────────────────
-- Everything below is hand-written. The columns above were generated by
-- drizzle-kit from schema.ts; the chain logic that uses them is not expressible
-- as table DDL.
--
-- SECURITY: the audit log was append-only but NOT reliably tamper-evident, and
-- nothing in the repo could check it either way.
--
-- audit_log exists to be evidence — CLAUDE.md §5 and §7.11 route every mutation
-- on tenants, memberships, roles, courses, enrollments and certificates through
-- it, for SOC 2 and for the accreditation audits customers pass using exported
-- platform evidence. Three defects in 0001:183-213 meant it could not carry that
-- weight, and db/README.md nonetheless claimed hash-chain integrity "passes".
--
-- ── Defect 1: the chain forks under concurrency ──────────────────────────
--
-- The trigger read its predecessor with a bare
--   select hash from audit_log where tenant_id … order by occurred_at desc, id desc limit 1
-- and took no lock. Two transactions committing at once both read the SAME
-- prev_hash and both succeeded, so two rows claimed one predecessor and the
-- "chain" became a tree — unverifiable, with no tampering required.
--
-- Worse, `occurred_at` defaults to now(), which in Postgres is TRANSACTION START,
-- not statement or commit time. A long transaction that starts first and commits
-- second lands earlier in occurred_at order than the row it actually chained
-- onto. So even serialised, chain order and occurred_at order disagreed.
--
-- Fixed with both halves, because either alone is insufficient:
--   * pg_advisory_xact_lock on the tenant's chain, taken as the trigger's first
--     statement and held to commit, so appends to one chain serialise; and
--   * ordering on the new `seq` bigserial rather than occurred_at. Under the
--     lock, seq order IS commit order for that chain, which is the property a
--     verifier needs. occurred_at stays as the business timestamp and is hashed,
--     but no longer decides position.
--
-- ── Defect 2: no canonicalisation and no delimiter ───────────────────────
--
-- Fields were concatenated bare:
--   canonical := coalesce(prev,'') || tenant_id || actor || action || resource_type || …
-- so the boundaries between them were invisible to the hash:
--   action='course.up' + resource_type='date'   hashes identically to
--   action='course.update' + resource_type=''
-- A forged row can be constructed to collide with a genuine one, which is
-- precisely the property a tamper-evident log must not have. Now hashed as a
-- canonical jsonb object: keys are unambiguous, and Postgres orders jsonb keys
-- deterministically so the text form is stable.
--
-- occurred_at is rendered as an explicit UTC pattern rather than ::text. The
-- text cast of a timestamptz depends on the session TimeZone GUC, so a verifier
-- running in another timezone would have recomputed different hashes and
-- reported an intact chain as forged.
--
-- ── Defect 3: the provenance fields were not hashed ──────────────────────
--
-- id, ip and user_agent were all excluded — exactly the fields an attacker
-- rewrites to shift the blame for an action onto another actor or address, and
-- they could be edited freely without breaking the hash. All three are hashed now.
--
-- ── Existing rows ────────────────────────────────────────────────────────
--
-- Rows written before this migration were hashed by the old algorithm and cannot
-- be recomputed under the new one. They are marked hash_version = 1 rather than
-- being rewritten (rewriting them is exactly what the table forbids, and would
-- destroy the evidence it exists to hold). verify_audit_chain reports them
-- honestly: their LINK is still checked — a successor's prev_hash must equal the
-- stored hash — but their content hash is reported as unverifiable rather than
-- as tampered. Silently skipping them, or flagging them as forged, would each
-- mislead an auditor in a different direction.

-- Everything already in the table predates the new canonicalisation.
update public.audit_log set hash_version = 1;

-- ── The canonical form, defined ONCE ─────────────────────────────────────
-- The trigger and the verifier must agree exactly. If they each built their own
-- string, any future edit to one would report the whole chain as forged — a
-- false alarm indistinguishable from a real one. So both call this.
create or replace function public.audit_log_canonical(
  p_prev_hash text,
  p_id uuid,
  p_seq bigint,
  p_tenant_id uuid,
  p_actor_user_id uuid,
  p_action text,
  p_resource_type text,
  p_resource_id text,
  p_before jsonb,
  p_after jsonb,
  p_ip text,
  p_user_agent text,
  p_occurred_at timestamptz
) returns text language sql immutable as $$
  select jsonb_build_object(
    'prev_hash',     p_prev_hash,
    'id',            p_id::text,
    'seq',           p_seq,
    'tenant_id',     p_tenant_id::text,
    'actor_user_id', p_actor_user_id::text,
    'action',        p_action,
    'resource_type', p_resource_type,
    'resource_id',   p_resource_id,
    'before',        p_before,
    'after',         p_after,
    'ip',            p_ip,
    'user_agent',    p_user_agent,
    -- Explicit UTC rendering: ::text would vary with the session TimeZone.
    'occurred_at',   to_char(p_occurred_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
  )::text;
$$;

create or replace function public.audit_log_hash_chain()
returns trigger language plpgsql security definer set search_path = public, extensions as $$
declare
  prev text;
begin
  -- FIRST statement, before the predecessor is read. Held until commit, so
  -- concurrent appends to one tenant's chain serialise instead of forking.
  -- Keyed per tenant (the chain is per tenant), so unrelated tenants do not
  -- contend. hashtext gives the stable int the advisory-lock API needs.
  perform pg_advisory_xact_lock(
    hashtext('audit_log:' || coalesce(NEW.tenant_id::text, 'null'))
  );

  select a.hash into prev
  from audit_log a
  where a.tenant_id is not distinct from NEW.tenant_id
  order by a.seq desc
  limit 1;

  NEW.prev_hash := prev;
  NEW.hash_version := 2;
  NEW.hash := encode(
    digest(
      public.audit_log_canonical(
        prev, NEW.id, NEW.seq, NEW.tenant_id, NEW.actor_user_id,
        NEW.action, NEW.resource_type, NEW.resource_id,
        NEW.before, NEW.after, NEW.ip, NEW.user_agent, NEW.occurred_at
      ),
      'sha256'
    ),
    'hex'
  );
  return NEW;
end $$;

-- ── The verifier ─────────────────────────────────────────────────────────
--
-- There was none. A tamper-evident log with no way to check it is unfalsifiable
-- in both directions: nobody could demonstrate tampering, and nobody could
-- demonstrate its absence — which is the claim an audit actually needs.
--
-- Returns one row per problem found; an EMPTY result means the chain is intact.
-- Pass a tenant id, or null for the platform-level chain (rows whose tenant was
-- deleted keep tenant_id as a plain uuid — see 0012 — so they stay on their own
-- chain rather than moving to the null one).
create or replace function public.verify_audit_chain(tenant uuid)
returns table(seq bigint, id uuid, problem text)
language plpgsql stable security definer set search_path = public, extensions as $$
declare
  r record;
  expected_prev text := null;
  computed text;
begin
  for r in
    select * from audit_log a
    where a.tenant_id is not distinct from tenant
    order by a.seq asc
  loop
    -- Link integrity. Checkable for every row regardless of hash_version,
    -- because it compares against the predecessor's STORED hash.
    if r.prev_hash is distinct from expected_prev then
      seq := r.seq; id := r.id;
      problem := format(
        'broken link: prev_hash is %s, predecessor hash is %s',
        coalesce(r.prev_hash, '<null>'), coalesce(expected_prev, '<null>')
      );
      return next;
    end if;

    -- Content integrity. Only v2 rows can be recomputed.
    if r.hash_version = 2 then
      computed := encode(
        digest(
          public.audit_log_canonical(
            r.prev_hash, r.id, r.seq, r.tenant_id, r.actor_user_id,
            r.action, r.resource_type, r.resource_id,
            r.before, r.after, r.ip, r.user_agent, r.occurred_at
          ),
          'sha256'
        ),
        'hex'
      );
      if computed is distinct from r.hash then
        seq := r.seq; id := r.id;
        problem := 'row contents do not match its hash';
        return next;
      end if;
    else
      seq := r.seq; id := r.id;
      problem := format(
        'hash_version %s predates migration 0015; link checked, contents not verifiable',
        r.hash_version
      );
      return next;
    end if;

    expected_prev := r.hash;
  end loop;
  return;
end $$;

-- Only a platform admin should be able to run the verifier: its output
-- enumerates the shape of the log. The service role (Drizzle) is unrestricted.
revoke execute on function public.verify_audit_chain(uuid) from public, anon, authenticated;
revoke execute on function public.audit_log_canonical(
  text, uuid, bigint, uuid, uuid, text, text, text, jsonb, jsonb, text, text, timestamptz
) from public, anon, authenticated;

-- ── TRUNCATE bypasses a row-level trigger entirely ───────────────────────
--
-- forbid_mutation is FOR EACH ROW, and TRUNCATE fires no row triggers. So
-- `truncate audit_log` erased the entire append-only log without raising —
-- likewise progress_events, the record of what every learner actually did.
--
-- `authenticated` cannot truncate (it never had the privilege, and 0014 removed
-- its writes outright). The role that CAN is the application's own DATABASE_URL
-- role, which owns these tables and bypasses RLS — so the one connection the app
-- uses all day was also the one that could silently empty its own evidence.
-- Statement-level triggers close it; unlike a privilege, they cannot be
-- forgotten by a future grant.
create or replace function public.forbid_truncate()
returns trigger language plpgsql as $$
begin
  raise exception '% is append-only; TRUNCATE is not permitted', TG_TABLE_NAME;
end $$;

drop trigger if exists audit_log_no_truncate on public.audit_log;
create trigger audit_log_no_truncate
  before truncate on public.audit_log
  for each statement execute function public.forbid_truncate();

drop trigger if exists progress_events_no_truncate on public.progress_events;
create trigger progress_events_no_truncate
  before truncate on public.progress_events
  for each statement execute function public.forbid_truncate();
