/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fyghhlxsorprmjyzbaiw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5Z2hobHhzb3Jwcm1qeXpiYWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0Njc5NjAsImV4cCI6MjA4NTA0Mzk2MH0.cAg-Go8AagHK6IAECiQo-3AgxuSObjP7659Dvg3xJ6w"